### ISSUE TITLE
Work on visualization for LAU data

### ISSUE THREAD

**Issue by rsyoh-97** [econ-dashboard/econ-dashboard.github.io#36]

**Comment by miguelito34** [comment]
Axis titles can be edited per below by listing a "title" within the relevant axis' encoding. A main title can be added by listing a "title" element:

{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "Google's stock price over time.",
  "data": {"url": "data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "mark": "line",
  "encoding": {
    "x": {"field": "date", "type": "temporal", "title": "Quarter"},
    "y": {"field": "price", "type": "quantitative", "title": "Unemployment Rate"}
  },
  "title": {
    "text": "Hello",
    "subtitle": "This data was pulled from x."
  }
}
